# -*- coding: utf-8 -*-
"""EDA day 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DgQ9LjjmwMJHio1R7mxCgv9ohj7fxZSp
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""## **EDA**"""

df = pd.read_csv("/content/train.csv")
df.head()

df['Age'].describe()

df['Age'].plot(kind='hist',bins=20)

df['Age'].plot(kind='kde')

df['Age'].plot(kind='box')

df[df['Age']>65]

a=df['Age'].isnull().sum()

df.drop(a)



df[df['Fare'] > 250]



sns.heatmap(pd.crosstab(df['Survived'],df['Pclass'],normalize='columns')*100)

pd.crosstab(df['Survived'],df['Sex'],normalize='columns')*100

pd.crosstab(df['Survived'],df['Embarked'],normalize='columns')*100

pd.crosstab(df['Sex'],df['Embarked'],normalize='columns')*100

pd.crosstab(df['Pclass'],df['Embarked'],normalize='columns')*100

# survived and age

df[df['Survived'] == 1]['Age'].plot(kind='kde',label='Survived')
df[df['Survived'] == 0]['Age'].plot(kind='kde',label='Not Survived')

plt.legend()
plt.show()

"""### EDA"""

df = pd.read_csv("/content/data_center_hybrid.csv")
df.head()

df.sample()

df.tail()

df.shape

df.size

df.columns

df.index

df.dtypes

df.info()

df.describe()

df.isnull()

df.notnull()

df.sum()

df.dropna()

df.fillna(50)

df.duplicated()

df.drop_duplicates()

df.nunique()

df['City'].unique()

df.value_counts()

df.sort_values('Year')

df.min()

df.max()

df[['Year']].mean()

df[['Year']].median()

df[['Year']].mode()

df.std(numeric_only=True)

df.var(numeric_only=True)

df.corr(numeric_only=True)

df.cov(numeric_only=True)

df.groupby('Facility_Type')
df

df.count()

df.loc()

df.iloc()

df.query('Year > 2020')

df.rename(columns={'Year': 'Report_Year'})

df['Year'].plot(kind='hist',bins=20)

df.drop(a)

df.boxplot(column='Year')

sns.histplot(data=df, x='Facility_Type')

sns.scatterplot(data=df, x='Facility_Type', y='Year')
plt.title('Scatter Plot ')
plt.xlabel('Year')
plt.ylabel('Facility Type')
plt.show()

sns.countplot(data=df, x='Year')
plt.title('Count Plot')
plt.xlabel('Year')
plt.ylabel('Count')
plt.show()

sns.pairplot(df[['Facility_ID','Year','Facility_Type']].dropna(),hue='Facility_Type')
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot=True)

"""# LOAN APPROVAL ANALYSIS"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

a=pd.read_csv("/content/loan_sanction_train.csv")
a

df.head()

df.drop_duplicates(inplace=True)
df

sns.countplot(data=a, x='Loan_Status')
plt.title('Distribution of Loan Status')
plt.xlabel('Loan Status')
plt.ylabel('Count')
plt.show()

a.isnull().sum()

"""### Handling Missing Values

I will fill the missing values in `Gender`, `Married`, `Dependents`, `Self_Employed`, `Loan_Amount_Term`, and `Credit_History` with their respective modes. For `LoanAmount`, I will use the median as it is less sensitive to outliers.
"""

a['Gender'].fillna(a['Gender'].mode()[0], inplace=True)

a['Married'].fillna(a['Married'].mode()[0], inplace=True)

a['Dependents'].fillna(a['Dependents'].mode()[0], inplace=True)

a['Self_Employed'].fillna(a['Self_Employed'].mode()[0], inplace=True)

a['LoanAmount'].fillna(a['LoanAmount'].median(), inplace=True)

a['Loan_Amount_Term'].fillna(a['Loan_Amount_Term'].mode()[0], inplace=True)

a['Credit_History'].fillna(a['Credit_History'].mode()[0], inplace=True)

a.isnull().sum()

"""### Credit History Impact on Loan Approval

Let's visualize the relationship between `Credit_History` and `Loan_Status` and then calculate the approval rates for each credit history status.
"""

plt.figure(figsize=(8, 6))
sns.countplot(data=a, x='Credit_History', hue='Loan_Status', palette='viridis')
plt.title('Loan Status by Credit History')
plt.xlabel('Credit History (1: Good, 0: Bad)')
plt.ylabel('Count')
plt.show()

credit_history_loan_status = pd.crosstab(a['Credit_History'], a['Loan_Status'], normalize='index') * 100
display(credit_history_loan_status)

plt.figure(figsize=(8, 6))
credit_history_loan_status.plot(kind='bar', stacked=True, color=['salmon', 'lightgreen'])
plt.title('Percentage of Loan Status by Credit History')
plt.xlabel('Credit History (1: Good, 0: Bad)')
plt.ylabel('Percentage')
plt.xticks(rotation=0)
plt.legend(title='Loan Status')
plt.show()



plt.figure(figsize=(10, 6))
sns.histplot(a['LoanAmount'], kde=True, bins=30)
plt.title('Distribution of Loan Amount')
plt.xlabel('Loan Amount (in thousands)')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8, 4))
sns.boxplot(x=a['LoanAmount'])
plt.title('Box Plot of Loan Amount')
plt.xlabel('Loan Amount (in thousands)')
plt.show()

plt.figure(figsize=(8, 6))
sns.countplot(data=a, x='Gender', hue='Loan_Status', palette='viridis')
plt.title('Loan Status by Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

gender_loan_status = pd.crosstab(a['Gender'], a['Loan_Status'], normalize='index') * 100
display(gender_loan_status)

plt.figure(figsize=(8, 6))
gender_loan_status.plot(kind='bar', stacked=True, color=['salmon', 'lightgreen'])
plt.title('Percentage of Loan Status by Gender')
plt.xlabel('Gender')
plt.ylabel('Percentage')
plt.xticks(rotation=0)
plt.legend(title='Loan Status')
plt.show()

plt.figure(figsize=(8, 6))
sns.countplot(data=a, x='Married', hue='Loan_Status', palette='viridis')
plt.title('Loan Status by Married Status')
plt.xlabel('Married')
plt.ylabel('Count')
plt.show()

married_loan_status = pd.crosstab(a['Married'], a['Loan_Status'], normalize='index') * 100
display(married_loan_status)

plt.figure(figsize=(8, 6))
married_loan_status.plot(kind='bar', stacked=True, color=['salmon', 'lightgreen'])
plt.title('Percentage of Loan Status by Married Status')
plt.xlabel('Married')
plt.ylabel('Percentage')
plt.xticks(rotation=0)
plt.legend(title='Loan Status')
plt.show()

a=pd.read_excel("/content/file.xlsx")
a

display(a.head())

display(a.info())

display(a.describe(include='all'))

display(a.isnull().sum())

a.dropna(how='all', inplace=True)

print('Shape of DataFrame after dropping all NaN rows:', a.shape)
display(a.isnull().sum())

plt.figure(figsize=(12, 7))
sns.countplot(data=a, y='Product_Category', order=a['Product_Category'].value_counts().index, palette='viridis')
plt.title('Distribution of Product Categories')
plt.xlabel('Count')
plt.ylabel('Product Category')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(a['Online_Spend'].dropna(), kde=True, color='skyblue', label='Online Spend')
sns.histplot(a['Offline_Spend'].dropna(), kde=True, color='salmon', label='Offline Spend')
plt.title('Distribution of Online and Offline Spending')
plt.xlabel('Amount Spent')
plt.ylabel('Frequency')
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=a, x='Offline_Spend', y='Online_Spend', hue='Gender', alpha=0.6, palette='coolwarm')
plt.title('Online vs. Offline Spend by Gender')
plt.xlabel('Offline Spend')
plt.ylabel('Online Spend')
plt.xscale('log')
plt.yscale('log')
plt.show()

a.dropna(subset=['CustomerID'], inplace=True)

a['Coupon_Code'].fillna('No Coupon', inplace=True)
a['Discount_pct'].fillna(0, inplace=True)

print('Shape of DataFrame after further cleaning:', a.shape)
display(a.isnull().sum())

a['Total_Spend'] = a['Online_Spend'] + a['Offline_Spend']

a['Transaction_Date'] = pd.to_datetime(a['Transaction_Date'])

display(a[['Online_Spend', 'Offline_Spend', 'Total_Spend']].head())

customer_data = a.groupby('CustomerID').agg(
    Total_Spend=('Total_Spend', 'sum'),
    Avg_Transaction_Spend=('Total_Spend', 'mean'),
    Num_Transactions=('Transaction_ID', 'count'),
    Avg_Quantity=('Quantity', 'mean'),
    Avg_Delivery_Charges=('Delivery_Charges', 'mean'),
    Avg_Discount_pct=('Discount_pct', 'mean'),
    Gender=('Gender', lambda x: x.mode()[0]),
    Location=('Location', lambda x: x.mode()[0]),
    Tenure_Months=('Tenure_Months', 'mean')
).reset_index()
display(customer_data.head())

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

numerical_features = ['Total_Spend', 'Avg_Transaction_Spend', 'Num_Transactions', 'Avg_Quantity', 'Avg_Delivery_Charges', 'Avg_Discount_pct', 'Tenure_Months']
categorical_features = ['Gender', 'Location']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ])

pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

customer_data_processed = pipeline.fit_transform(customer_data)

print('Shape of processed data:', customer_data_processed.shape)

from sklearn.cluster import KMeans

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10)
    kmeans.fit(customer_data_processed)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('WCSS')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

k_optimal = 4

kmeans = KMeans(n_clusters=k_optimal, init='k-means++', random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(customer_data_processed)

customer_data['Cluster'] = cluster_labels
display(customer_data.head())

segment_analysis = customer_data.groupby('Cluster')[numerical_features + categorical_features].mean(numeric_only=True)

for feature in categorical_features:
    segment_analysis = pd.concat([segment_analysis, customer_data.groupby('Cluster')[feature].value_counts(normalize=True).unstack()], axis=1)

display(segment_analysis)

plt.figure(figsize=(10, 6))
sns.barplot(x=segment_analysis.index, y='Total_Spend', data=segment_analysis, palette='viridis')
plt.title('Total Spend by Customer Segment')
plt.xlabel('Customer Segment (Cluster)')
plt.ylabel('Average Total Spend')
plt.show()

merged_data = pd.merge(a, customer_data[['CustomerID', 'Cluster']], on='CustomerID', how='left')

plt.figure(figsize=(14, 8))
sns.countplot(data=merged_data, y='Product_Category', hue='Cluster', palette='viridis', order=merged_data['Product_Category'].value_counts().index)
plt.title('Product Category Distribution by Customer Segment')
plt.xlabel('Count')
plt.ylabel('Product Category')
plt.legend(title='Cluster')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x=segment_analysis.index, y='Num_Transactions', data=segment_analysis, palette='viridis')
plt.title('Average Number of Transactions by Customer Segment')
plt.xlabel('Customer Segment (Cluster)')
plt.ylabel('Average Number of Transactions')
plt.show()

